const Images={
    AiIcon:require("../../assets/ai_icon.png").default,
    add_icon:require("../../assets/add_icon.png").default,
    arrow_back:require("../../assets/arrow_back.png").default,
    bell_notification:require("../../assets/bell_notification.png").default,
    breakfast_icon:require("../../assets/breakfast_icon.png").default,
    Confirmation_icon:require("../../assets/Confirmation_icon.png").default,
    Confirmation_positive_icon:require("../../assets/Confirmation_positive_icon.png").default,
    cross_icon:require("../../assets/cross_icon.png").default,
    Daily_calories_intake:require("../../assets/Daily_calories_intake.png").default,
    dinner_icon:require("../../assets/dinner_icon.png").default,
    Female_icon:require("../../assets/Female_icon.png").default,
    filter_icon:require("../../assets/filter_icon.png").default,
    find_coach:require("../../assets/find_coach.png").default,
    food_icon:require("../../assets/food_icon.png").default,
    home_icon:require("../../assets/home.png").default,
    Log_cal_nav:require("../../assets/Log_cal_nav.png").default,
    Log_weight_nav:require("../../assets/Log_weight_nav.png").default,
    logo_white:require("../../assets/logo_white.png").default,
    logo_apple:require("../../assets/logo_apple.png").default,
    logo_facebook:require("../../assets/logo_facebook.png").default,
    lunch_icon:require("../../assets/lunch_icon.png").default,
    Male_icon:require("../../assets/Male_icon.png").default,
    Message_a_coach:require("../../assets/Message_a_coach.png").default,
    Messages_nav:require("../../assets/Messages_nav.png").default,
    My_progress_nav:require("../../assets/My_progress_nav.png").default,
    Profile_nav:require("../../assets/Profile_nav.png").default,
    scan_camera_icon:require("../../assets/scan_camera_icon.png").default,
    search_icon:require("../../assets/search_icon.png").default,
    snack_icon:require("../../assets/snack_icon.png").default,
    todays_calories_intake:require("../../assets/todays_calories_intake.png").default,
    google_icon:require("../../assets/google_icon.png").default,

}

export default Images;